//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 09:21:37 AM CST 
//


package com.walmart.fraudengine.jaxb.csc.response;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.walmart.fraudengine.jaxb.csc.response.Adapter2;
import com.walmart.fraudengine.jaxb.csc.response.FraudReviewResponse;


/**
 * <p>Java class for fraudReviewResponse element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="fraudReviewResponse">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="metaInfo">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CSCServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="response">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="agentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="action">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="ACCEPT"/>
 *                           &lt;enumeration value="DENY"/>
 *                           &lt;enumeration value="ORDER_CANCELLED_ACK"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="actionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                     &lt;element name="agentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="requestId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaInfo",
    "response"
})
@XmlRootElement(name = "fraudReviewResponse")
public class FraudReviewResponse {

    @XmlElement(nillable = true)
    protected MetaInfo metaInfo;
    @XmlElement(nillable = true)
    protected Response response;

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MetaInfo }
     *     
     */
    public MetaInfo getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaInfo }
     *     
     */
    public void setMetaInfo(MetaInfo value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     *  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="CSCServerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cscServerName" 
    })
    public static class MetaInfo {

        @XmlElement(name = "CSCServerName")
        protected String cscServerName;

        /**
         * Gets the value of the cscServerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCSCServerName() {
            return cscServerName;
        }

        /**
         * Sets the value of the cscServerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCSCServerName(String value) {
            this.cscServerName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="agentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="action">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="ACCEPT"/>
     *               &lt;enumeration value="DENY"/>
     *               &lt;enumeration value="ORDER_CANCELLED_ACK"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="actionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="agentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="requestId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderId",
        "agentId",
        "reasonCode",
        "action",
        "actionTime",
        "agentDescription"
    })
    public static class Response {

        /**
		 * @return the reasonCode
		 */
		public String getReasonCode() {
			return reasonCode;
		}

		/**
		 * @param reasonCode the reasonCode to set
		 */
		public void setReasonCode(String reasonCode) {
			this.reasonCode = reasonCode;
		}

		protected String orderId;
        protected String agentId;
        protected String reasonCode;
        protected String action;
        @XmlElement(type = String.class, nillable = true)
        @XmlJavaTypeAdapter(Adapter2 .class)
        protected Calendar actionTime;
        protected String agentDescription;
        @XmlAttribute(required = true)
        protected String requestId;

        /**
         * Gets the value of the orderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderId() {
            return orderId;
        }

        /**
         * Sets the value of the orderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderId(String value) {
            this.orderId = value;
        }

        /**
         * Gets the value of the agentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgentId() {
            return agentId;
        }

        /**
         * Sets the value of the agentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgentId(String value) {
            this.agentId = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the actionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Calendar getActionTime() {
            return actionTime;
        }

        /**
         * Sets the value of the actionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionTime(Calendar value) {
            this.actionTime = value;
        }

        /**
         * Gets the value of the agentDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgentDescription() {
            return agentDescription;
        }

        /**
         * Sets the value of the agentDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgentDescription(String value) {
            this.agentDescription = value;
        }

        /**
         * Gets the value of the requestId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestId() {
            return requestId;
        }

        /**
         * Sets the value of the requestId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestId(String value) {
            this.requestId = value;
        }

    }

}
