//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 09:21:37 AM CST 
//


package com.walmart.fraudengine.jaxb.csc.response;

import javax.xml.bind.annotation.XmlRegistry;
import com.walmart.fraudengine.jaxb.csc.response.FraudReviewResponse;
import com.walmart.fraudengine.jaxb.csc.response.FraudReviewResponse.MetaInfo;
import com.walmart.fraudengine.jaxb.csc.response.FraudReviewResponse.Response;
import com.walmart.fraudengine.jaxb.csc.response.ObjectFactory;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.walmart.fraudengine.jaxb.csc.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.walmart.fraudengine.jaxb.csc.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createFraudReviewResponseResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link MetaInfo }
     * 
     */
    public MetaInfo createFraudReviewResponseMetaInfo() {
        return new MetaInfo();
    }

    /**
     * Create an instance of {@link FraudReviewResponse }
     * 
     */
    public FraudReviewResponse createFraudReviewResponse() {
        return new FraudReviewResponse();
    }

}
