//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.07 at 12:23:33 PM CST 
//

package com.walmart.fraudengine.jaxb.oms.response;

import javax.xml.bind.annotation.XmlRegistry;
import com.walmart.fraudengine.jaxb.oms.response.Extn;
import com.walmart.fraudengine.jaxb.oms.response.ObjectFactory;
import com.walmart.fraudengine.jaxb.oms.response.Order;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.walmart.fraudengine.jaxb.oms.response
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.walmart.fraudengine.jaxb.oms.response
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Extn }
	 * 
	 */
	public Extn createExtn() {
		return new Extn();
	}

	/**
	 * Create an instance of {@link Order }
	 * 
	 */
	public Order createOrder() {
		return new Order();
	}

	/**
	 * Create an instance of {@link FraudReviewResponseOMS }
	 * 
	 */
	public FraudReviewResponseOMS createFraudReviewResponseOMS() {
		return new FraudReviewResponseOMS();
	}

	/**
	 * Create an instance of {@link FraudReviewResponseOMS.MetaInfo }
	 * 
	 */
	public FraudReviewResponseOMS.MetaInfo createFraudReviewResponseOMSMetaInfo() {
		return new FraudReviewResponseOMS.MetaInfo();
	}

	/**
	 * Create an instance of {@link FraudReviewResponseOMS.Response }
	 * 
	 */
	public FraudReviewResponseOMS.Response createFraudReviewResponseOMSResponse() {
		return new FraudReviewResponseOMS.Response();
	}

}
