//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.07 at 01:07:40 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://chinaGM.walmart.com/fraudreview")
package com.walmart.fraudengine.jaxb.csc.request;
