//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.07 at 01:07:40 PM CST 
//


package com.walmart.fraudengine.jaxb.csc.request;

import java.util.Calendar;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import com.walmart.fraudengine.jaxb.csc.request.Adapter2;

/**
* Description:This class is used to convert some value to a date.
* @author: 
* @Version:
* Copyright: 2010-2011 Wal-Mart China All rights reserved
*/
public class Adapter2 extends XmlAdapter<String, Calendar>
{

	/**
     * Description:This method is used to convert a string to a date.
     * @param <value> String
     * @return <<return DateTimeConverter.parseDateTime(value)>>
     */
    public Calendar unmarshal(String value) {
        return DateTimeConverter.parseDateTime(value);
    }

    /**
     * Description:This method is used to convert a calendar value to a date.
     * @param <value> Calendar
     * @return <<return DateTimeConverter.printDateTime(value)>>
     */
    public String marshal(Calendar value) {
        return DateTimeConverter.printDateTime(value);
    }

}
