//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 09:21:37 AM CST 
//


package com.walmart.fraudengine.jaxb.csc.response;

import java.util.Calendar;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import com.walmart.fraudengine.jaxb.csc.request.DateConverter;
import com.walmart.fraudengine.jaxb.csc.response.Adapter1;

/**
* Description:This class is used to convert some value to a date.
* @author: 
* @Version:
* Copyright: 2010-2011 Wal-Mart China All rights reserved
*/
public class Adapter1 extends XmlAdapter<String, Calendar>
{

	/**
     * Description:This method is used to convert a string to a date.
     * @param <value> String
     * @return <<return DateConverter.parseDate(value)>>
     */
    public Calendar unmarshal(String value) {
        return DateConverter.parseDate(value);
    }
    
    /**
     * Description:This method is used to convert a calendar value to a date.
     * @param <value> Calendar
     * @return <<return DateConverter.printDate(value)>>
     */
    public String marshal(Calendar value) {
        return DateConverter.printDate(value);
    }

}
