insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (41, 'ä¸Šæµ·å¸å»¶å®‰è¥¿è·¯1118å·é¾™ä¹æ¢¦å¤§åŽ¦', 'N', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', 1, 4, 'Billing address of customer', 41, 'FIELD_LONG_DESC	Billing address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (42, 'elsie_sun', 'N', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', 1, 6, 'Alipay account of customer', 15, 'FIELD_LONG_DESC	Alipay account of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (43, '172.0.0.22', 'N', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', '01-AUG-11 02.20.43.000000 AM', 'SYSTEM', 1, 7, 'IP address of customer', 16, 'FIELD_LONG_DESC	IP address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (61, '1118WestYan''anRoad', 'N', '07-AUG-11 10.46.11.000000 PM', 'SYSTEM', '07-AUG-11 10.46.11.000000 PM', 'SYSTEM', 1, 3, 'Shipping address of customer', 3, 'FIELD_LONG_DESC	Shipping address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (62, '172.0.0.11', 'N', '07-AUG-11 10.50.20.000000 PM', 'SYSTEM', '07-AUG-11 10.50.20.000000 PM', 'SYSTEM', 1, 7, 'IP address of customer', 62, 'FIELD_LONG_DESC	IP address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (63, '1118WestYan''anRoad', 'N', '07-AUG-11 10.52.01.000000 PM', 'SYSTEM', '07-AUG-11 10.52.01.000000 PM', 'SYSTEM', 1, 4, 'Billing address of customer', 61, 'FIELD_LONG_DESC	Billing address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (64, 'elsie.sun@bleum.com', 'N', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', 1, 1, 'Email address of customer', 7, 'FIELD_LONG_DESC	Email address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (65, '021-22222222', 'N', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', 1, 5, 'Phone number of customer', 9, 'FIELD_LONG_DESC	Phone numberc of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (66, '172.0.0.33', 'N', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', '07-AUG-11 10.56.54.000000 PM', 'SYSTEM', 1, 7, 'IP address of customer', 63, 'FIELD_LONG_DESC	IP address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (67, 'Jack.wang', 'N', '07-AUG-11 11.07.57.000000 PM', 'SYSTEM', '07-AUG-11 11.07.57.000000 PM', 'SYSTEM', 1, 2, 'ID of customer', 11, 'FIELD_LONG_DESC	ID of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (68, '021-33333333', 'N', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', 1, 5, 'Phone number of customer', 14, 'FIELD_LONG_DESC	Phone number of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (69, 'ä¸Šæµ·å¸åäº¬ä¸œè·¯8888å·', 'N', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', 1, 3, 'Shipping address of customer', 13, 'FIELD_LONG_DESC	Shipping address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (70, 'ä¸Šæµ·å¸æ±Ÿèè·¯1å·', 'N', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', '07-AUG-11 11.07.58.000000 PM', 'SYSTEM', 1, 4, 'Billing address of customer', 64, 'FIELD_LONG_DESC	Billingc address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (1, 'wchen@walmart.com', 'N', '22-JUL-11 01.23.11.000000 AM', 'SYSTEM', '22-JUL-11 01.23.11.000000 AM', 'SYSTEM', 1, 1, 'email address of customer', 2, 'FIELD_LONG_DESC	email address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (3, 'ggao@walmart.com', 'N', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', 1, 1, 'email address of customer', 12, 'FIELD_LONG_DESC	email address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (4, 'Rainie.Liu', 'N', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', 1, 2, 'id of customer', 1, 'FIELD_LONG_DESC	id of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (5, 'Dick.Shi', 'N', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', 1, 2, 'id of customer', 6, 'FIELD_LONG_DESC	id of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (7, '1111-1111', 'N', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', 1, 5, 'phone number of customer', 4, 'FIELD_LONG_DESC	phone number of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (11, 'ä¸Šæµ·å¸é™å®‰åŒºå¸¸ç†Ÿè·¯8å·', 'N', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', '22-JUL-11 01.23.12.000000 AM', 'SYSTEM', 1, 3, 'shipping address of customer', 8, 'FIELD_LONG_DESC shipping address of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (21, 'Tom_Zhang', 'N', '07-SEP-11 07.18.49.000000 PM', 'SYSTEM', '07-SEP-11 07.18.49.000000 PM', 'SYSTEM', 1, 6, 'Alipay account of customer', 5, 'FIELD_LONG_DESC	Alipay account of customer');

insert into pos_neg_list (POS_NEG_LIST_PK, FIELD_VALUE, SOFT_DELETE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, VERSION, FIELD_TYPE_FK, FIELD_SHORT_DESC, POS_NEG_REASON_FK, FIELD_LONG_DESC)
values (22, 'Bruce_Zhao', 'N', '07-SEP-11 07.18.49.000000 PM', 'SYSTEM', '07-SEP-11 07.18.49.000000 PM', 'SYSTEM', 1, 6, 'Alipay account of customer', 10, 'FIELD_LONG_DESC	Alipay account of customer');

