CREATE TABLE USER_DETAIL
(
           "USER_DETAIL_PK"  NUMBER NOT NULL ENABLE,----USER_DETAIL_PRIMARY KEY
           "LOGIN_IP_ADDRESS" VARCHAR2(30),        ---EVERY TIME USER LOGIN IP
		    "LOGIN_DATE"  TIMESTAMP (6) NOT NULL ENABLE, --EVERY TIME USER LOGIN DATE
            "SOFT_DELETE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, ---- soft delete
      		"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, ---------create date
      		"CREATED_BY" VARCHAR2(40) NOT NULL ENABLE, ---------create by
			"VERSION" NUMBER NOT NULL ENABLE, 
			"USER_MASTER_FK" NUMBER,
  CONSTRAINT "PK_USER_DETAIL" PRIMARY KEY ("USER_DETAIL_PK")
);
ALTER TABLE USER_DETAIL ADD CONSTRAINT USER_DETAIL_USER_MASTER_FK FOREIGN KEY(USER_MASTER_FK) REFERENCES USER_MASTER(USER_MASTER_PK);

