// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.walmart.fraudengine.jaxb.oms.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.walmart.fraudengine.jaxb.oms.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaymentMethods }
     * 
     */
    public PaymentMethods createPaymentMethods() {
        return new PaymentMethods();
    }

    /**
     * Create an instance of {@link LineCharges }
     * 
     */
    public LineCharges createLineCharges() {
        return new LineCharges();
    }

    /**
     * Create an instance of {@link LineCharge }
     * 
     */
    public LineCharge createLineCharge() {
        return new LineCharge();
    }

    /**
     * Create an instance of {@link Extn }
     * 
     */
    public Extn createExtn() {
        return new Extn();
    }

    /**
     * Create an instance of {@link LinePriceInfo }
     * 
     */
    public LinePriceInfo createLinePriceInfo() {
        return new LinePriceInfo();
    }

    /**
     * Create an instance of {@link PaymentMethod }
     * 
     */
    public PaymentMethod createPaymentMethodsPaymentMethod() {
        return new PaymentMethod();
    }

    /**
     * Create an instance of {@link OrderLine }
     * 
     */
    public OrderLine createOrderLine() {
        return new OrderLine();
    }

    /**
     * Create an instance of {@link PersonInfoBillTo }
     * 
     */
    public PersonInfoBillTo createPersonInfoBillTo() {
        return new PersonInfoBillTo();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link PaymentDetails }
     * 
     */
    public PaymentDetails createPaymentDetails() {
        return new PaymentDetails();
    }

    /**
     * Create an instance of {@link OrderLines }
     * 
     */
    public OrderLines createOrderLines() {
        return new OrderLines();
    }

    /**
     * Create an instance of {@link OrderDate }
     * 
     */
    public OrderDate createOrderDate() {
        return new OrderDate();
    }

    /**
     * Create an instance of {@link PersonInfoShipTo }
     * 
     */
    public PersonInfoShipTo createPersonInfoShipTo() {
        return new PersonInfoShipTo();
    }

    /**
     * Create an instance of {@link PriceInfo }
     * 
     */
    public PriceInfo createPriceInfo() {
        return new PriceInfo();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OrderDates }
     * 
     */
    public OrderDates createOrderDates() {
        return new OrderDates();
    }

}
