//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 03:34:40 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.Item;
import com.walmart.fraudengine.jaxb.oms.request.LineCharges;
import com.walmart.fraudengine.jaxb.oms.request.LinePriceInfo;
import com.walmart.fraudengine.jaxb.oms.request.OrderLine;
import com.walmart.fraudengine.jaxb.oms.request.PersonInfoShipTo;


/**
 * <p>Java class for OrderLine element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="OrderLine">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Item"/>
 *           &lt;element ref="{}PersonInfoShipTo" minOccurs="0"/>
 *           &lt;element ref="{}LinePriceInfo"/>
 *           &lt;element ref="{}LineCharges"/>
 *         &lt;/sequence>
 *         &lt;attribute name="OrderedQty" type="{http://www.w3.org/2001/XMLSchema}double" />
 *         &lt;attribute name="PrimeLineNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *         &lt;attribute name="SubLineNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "personInfoShipTo",
    "linePriceInfo",
    "lineCharges"
})
@XmlRootElement(name = "OrderLine")
public class OrderLine {

    @XmlElement(name = "Item")
    protected Item item;
    @XmlElement(name = "PersonInfoShipTo")
    protected PersonInfoShipTo personInfoShipTo;
    @XmlElement(name = "LinePriceInfo")
    protected LinePriceInfo linePriceInfo;
    @XmlElement(name = "LineCharges")
    protected LineCharges lineCharges;
    @XmlAttribute(name = "OrderedQty")
    protected Double orderedQty;
    @XmlAttribute(name = "PrimeLineNo")
    protected Integer primeLineNo;
    @XmlAttribute(name = "SubLineNo")
    protected Integer subLineNo;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the personInfoShipTo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfoShipTo }
     *     
     */
    public PersonInfoShipTo getPersonInfoShipTo() {
        return personInfoShipTo;
    }

    /**
     * Sets the value of the personInfoShipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfoShipTo }
     *     
     */
    public void setPersonInfoShipTo(PersonInfoShipTo value) {
        this.personInfoShipTo = value;
    }

    /**
     * Gets the value of the linePriceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LinePriceInfo }
     *     
     */
    public LinePriceInfo getLinePriceInfo() {
        return linePriceInfo;
    }

    /**
     * Sets the value of the linePriceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinePriceInfo }
     *     
     */
    public void setLinePriceInfo(LinePriceInfo value) {
        this.linePriceInfo = value;
    }

    /**
     * Gets the value of the lineCharges property.
     * 
     * @return
     *     possible object is
     *     {@link LineCharges }
     *     
     */
    public LineCharges getLineCharges() {
        return lineCharges;
    }

    /**
     * Sets the value of the lineCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineCharges }
     *     
     */
    public void setLineCharges(LineCharges value) {
        this.lineCharges = value;
    }

    /**
     * Gets the value of the orderedQty property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOrderedQty() {
        return orderedQty;
    }

    /**
     * Sets the value of the orderedQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOrderedQty(Double value) {
        this.orderedQty = value;
    }

    /**
     * Gets the value of the primeLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrimeLineNo() {
        return primeLineNo;
    }

    /**
     * Sets the value of the primeLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrimeLineNo(Integer value) {
        this.primeLineNo = value;
    }

    /**
     * Gets the value of the subLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubLineNo() {
        return subLineNo;
    }

    /**
     * Sets the value of the subLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubLineNo(Integer value) {
        this.subLineNo = value;
    }

}
