//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 03:34:40 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.PaymentDetails;


/**
 * <p>Java class for PaymentDetails element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="PaymentDetails">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="AuditTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ChargeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ProcessedAmount" type="{http://www.w3.org/2001/XMLSchema}double" />
 *         &lt;attribute name="RequestProcessed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PaymentDetails")
public class PaymentDetails {

    @XmlAttribute(name = "AuditTransactionId")
    protected String auditTransactionId;
    @XmlAttribute(name = "ChargeType")
    protected String chargeType;
    @XmlAttribute(name = "ProcessedAmount")
    protected Double processedAmount;
    @XmlAttribute(name = "RequestProcessed")
    protected String requestProcessed;

    /**
     * Gets the value of the auditTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditTransactionId() {
        return auditTransactionId;
    }

    /**
     * Sets the value of the auditTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditTransactionId(String value) {
        this.auditTransactionId = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the processedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProcessedAmount() {
        return processedAmount;
    }

    /**
     * Sets the value of the processedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProcessedAmount(Double value) {
        this.processedAmount = value;
    }

    /**
     * Gets the value of the requestProcessed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestProcessed() {
        return requestProcessed;
    }

    /**
     * Sets the value of the requestProcessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestProcessed(String value) {
        this.requestProcessed = value;
    }

}
