package com.walmart.fraudengine.rules.resources.drl;

import com.walmart.fraudengine.rules.RuleEngineOrder;
import com.walmart.fraudengine.util.FraudCheckConst;
import com.walmart.fraudengine.rules.RuleOrderStatus;

global RuleOrderStatus orderStatus;

rule "challenge_mop_is_ALIPAY_total_amount_greater_than_8000"
	salience 99
	when
		$order: Order(hitSomeRule == false)
	then
		$order.setHitSomeRule(true);
end