//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 03:34:40 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.Extn;


/**
 * <p>Java class for Extn element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Extn">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="CustomerAccountAge" type="{http://www.w3.org/2001/XMLSchema}int" />
 *         &lt;attribute name="CustomerIPAddr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="FraudLastTransactionID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="VisitorNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Extn")
public class Extn {

    @XmlAttribute(name = "CustomerAccountAge")
    protected Integer customerAccountAge;
    @XmlAttribute(name = "CustomerIPAddr")
    protected String customerIPAddr;
    @XmlAttribute(name = "FraudLastTransactionID")
    protected String fraudLastTransactionID;
    @XmlAttribute(name = "VisitorNo")
    protected String visitorNo;

    /**
     * Gets the value of the customerAccountAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCustomerAccountAge() {
        return customerAccountAge;
    }

    /**
     * Sets the value of the customerAccountAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCustomerAccountAge(Integer value) {
        this.customerAccountAge = value;
    }

    /**
     * Gets the value of the customerIPAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerIPAddr() {
        return customerIPAddr;
    }

    /**
     * Sets the value of the customerIPAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerIPAddr(String value) {
        this.customerIPAddr = value;
    }

    /**
     * Gets the value of the fraudLastTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudLastTransactionID() {
        return fraudLastTransactionID;
    }

    /**
     * Sets the value of the fraudLastTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudLastTransactionID(String value) {
        this.fraudLastTransactionID = value;
    }

    /**
     * Gets the value of the visitorNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitorNo() {
        return visitorNo;
    }

    /**
     * Sets the value of the visitorNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitorNo(String value) {
        this.visitorNo = value;
    }

}
