//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 03:34:40 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.LineCharge;


/**
 * <p>Java class for LineCharge element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="LineCharge">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="ChargeCategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ChargeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ChargePerLine" type="{http://www.w3.org/2001/XMLSchema}double" />
 *         &lt;attribute name="ChargePerUnit" type="{http://www.w3.org/2001/XMLSchema}double" />
 *         &lt;attribute name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LineCharge")
public class LineCharge {

    @XmlAttribute(name = "ChargeCategory")
    protected String chargeCategory;
    @XmlAttribute(name = "ChargeName")
    protected String chargeName;
    @XmlAttribute(name = "ChargePerLine")
    protected Double chargePerLine;
    @XmlAttribute(name = "ChargePerUnit")
    protected Double chargePerUnit;
    @XmlAttribute(name = "Reference")
    protected String reference;

    /**
     * Gets the value of the chargeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeCategory() {
        return chargeCategory;
    }

    /**
     * Sets the value of the chargeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeCategory(String value) {
        this.chargeCategory = value;
    }

    /**
     * Gets the value of the chargeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeName() {
        return chargeName;
    }

    /**
     * Sets the value of the chargeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeName(String value) {
        this.chargeName = value;
    }

    /**
     * Gets the value of the chargePerLine property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getChargePerLine() {
        return chargePerLine;
    }

    /**
     * Sets the value of the chargePerLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setChargePerLine(Double value) {
        this.chargePerLine = value;
    }

    /**
     * Gets the value of the chargePerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getChargePerUnit() {
        return chargePerUnit;
    }

    /**
     * Sets the value of the chargePerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setChargePerUnit(Double value) {
        this.chargePerUnit = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

}
