//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 03:34:40 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.Extn;
import com.walmart.fraudengine.jaxb.oms.request.Order;
import com.walmart.fraudengine.jaxb.oms.request.OrderDates;
import com.walmart.fraudengine.jaxb.oms.request.OrderLines;
import com.walmart.fraudengine.jaxb.oms.request.PaymentMethods;
import com.walmart.fraudengine.jaxb.oms.request.PersonInfoBillTo;
import com.walmart.fraudengine.jaxb.oms.request.PersonInfoShipTo;
import com.walmart.fraudengine.jaxb.oms.request.PriceInfo;


/**
 * <p>Java class for Order element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Order">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Extn"/>
 *           &lt;element ref="{}PriceInfo"/>
 *           &lt;element ref="{}OrderLines"/>
 *           &lt;element ref="{}PersonInfoShipTo"/>
 *           &lt;element ref="{}PersonInfoBillTo"/>
 *           &lt;element ref="{}PaymentMethods"/>
 *           &lt;element ref="{}OrderDates"/>
 *         &lt;/sequence>
 *         &lt;attribute name="CustomerContactID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="CustomerEMailID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="EntryType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="OrderNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="PaymentStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="Status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extn",
    "priceInfo",
    "orderLines",
    "personInfoShipTo",
    "personInfoBillTo",
    "paymentMethods",
    "orderDates"
})
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "Extn")
    protected Extn extn;
    @XmlElement(name = "PriceInfo")
    protected PriceInfo priceInfo;
    @XmlElement(name = "OrderLines")
    protected OrderLines orderLines;
    @XmlElement(name = "PersonInfoShipTo")
    protected PersonInfoShipTo personInfoShipTo;
    @XmlElement(name = "PersonInfoBillTo")
    protected PersonInfoBillTo personInfoBillTo;
    @XmlElement(name = "PaymentMethods")
    protected PaymentMethods paymentMethods;
    @XmlElement(name = "OrderDates")
    protected OrderDates orderDates;
    @XmlAttribute(name = "CustomerContactID")
    protected String customerContactID;
    @XmlAttribute(name = "CustomerEMailID")
    protected String customerEMailID;
    @XmlAttribute(name = "DocumentType")
    protected String documentType;
    @XmlAttribute(name = "EnterpriseCode")
    protected String enterpriseCode;
    @XmlAttribute(name = "EntryType")
    protected String entryType;
    @XmlAttribute(name = "OrderDate")
    protected String orderDate;
    @XmlAttribute(name = "OrderNo")
    protected String orderNo;
    @XmlAttribute(name = "OrderType")
    protected String orderType;
    @XmlAttribute(name = "PaymentStatus")
    protected String paymentStatus;
    @XmlAttribute(name = "Status")
    protected String status;

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link Extn }
     *     
     */
    public Extn getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extn }
     *     
     */
    public void setExtn(Extn value) {
        this.extn = value;
    }

    /**
     * Gets the value of the priceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PriceInfo }
     *     
     */
    public PriceInfo getPriceInfo() {
        return priceInfo;
    }

    /**
     * Sets the value of the priceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceInfo }
     *     
     */
    public void setPriceInfo(PriceInfo value) {
        this.priceInfo = value;
    }

    /**
     * Gets the value of the orderLines property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLines }
     *     
     */
    public OrderLines getOrderLines() {
        return orderLines;
    }

    /**
     * Sets the value of the orderLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLines }
     *     
     */
    public void setOrderLines(OrderLines value) {
        this.orderLines = value;
    }

    /**
     * Gets the value of the personInfoShipTo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfoShipTo }
     *     
     */
    public PersonInfoShipTo getPersonInfoShipTo() {
        return personInfoShipTo;
    }

    /**
     * Sets the value of the personInfoShipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfoShipTo }
     *     
     */
    public void setPersonInfoShipTo(PersonInfoShipTo value) {
        this.personInfoShipTo = value;
    }

    /**
     * Gets the value of the personInfoBillTo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfoBillTo }
     *     
     */
    public PersonInfoBillTo getPersonInfoBillTo() {
        return personInfoBillTo;
    }

    /**
     * Sets the value of the personInfoBillTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfoBillTo }
     *     
     */
    public void setPersonInfoBillTo(PersonInfoBillTo value) {
        this.personInfoBillTo = value;
    }

    /**
     * Gets the value of the paymentMethods property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethods }
     *     
     */
    public PaymentMethods getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * Sets the value of the paymentMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethods }
     *     
     */
    public void setPaymentMethods(PaymentMethods value) {
        this.paymentMethods = value;
    }

    /**
     * Gets the value of the orderDates property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDates }
     *     
     */
    public OrderDates getOrderDates() {
        return orderDates;
    }

    /**
     * Sets the value of the orderDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDates }
     *     
     */
    public void setOrderDates(OrderDates value) {
        this.orderDates = value;
    }

    /**
     * Gets the value of the customerContactID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerContactID() {
        return customerContactID;
    }

    /**
     * Sets the value of the customerContactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerContactID(String value) {
        this.customerContactID = value;
    }

    /**
     * Gets the value of the customerEMailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEMailID() {
        return customerEMailID;
    }

    /**
     * Sets the value of the customerEMailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEMailID(String value) {
        this.customerEMailID = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the entryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryType() {
        return entryType;
    }

    /**
     * Sets the value of the entryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryType(String value) {
        this.entryType = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentStatus(String value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
