//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 04:40:36 PM CST 
//


package com.walmart.fraudengine.jaxb.oms.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.walmart.fraudengine.jaxb.oms.request.PaymentDetails;
import com.walmart.fraudengine.jaxb.oms.request.PaymentMethod;
import com.walmart.fraudengine.jaxb.oms.request.PersonInfoBillTo;


/**
 * <p>Java class for PaymentMethod element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="PaymentMethod">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}PaymentDetails"/>
 *           &lt;element ref="{}PersonInfoBillTo"/>
 *         &lt;/sequence>
 *         &lt;attribute name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="PaymentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentDetails",
    "personInfoBillTo"
})
@XmlRootElement(name = "PaymentMethod")
public class PaymentMethod {

    @XmlElement(name = "PaymentDetails")
    protected PaymentDetails paymentDetails;
    @XmlElement(name = "PersonInfoBillTo")
    protected PersonInfoBillTo personInfoBillTo;
    @XmlAttribute(name = "CustomerAccountNo")
    protected String customerAccountNo;
    @XmlAttribute(name = "FirstName")
    protected String firstName;
	@XmlAttribute(name = "LastName")
    protected String lastName;
    @XmlAttribute(name = "PaymentType")
    protected String paymentType;

    /**
     * Gets the value of the paymentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetails }
     *     
     */
    public PaymentDetails getPaymentDetails() {
        return paymentDetails;
    }

    /**
     * Sets the value of the paymentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetails }
     *     
     */
    public void setPaymentDetails(PaymentDetails value) {
        this.paymentDetails = value;
    }

    /**
     * Gets the value of the personInfoBillTo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfoBillTo }
     *     
     */
    public PersonInfoBillTo getPersonInfoBillTo() {
        return personInfoBillTo;
    }

    /**
     * Sets the value of the personInfoBillTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfoBillTo }
     *     
     */
    public void setPersonInfoBillTo(PersonInfoBillTo value) {
        this.personInfoBillTo = value;
    }
    public String getCustomerAccountNo() {
		return customerAccountNo;
	}

	public void setCustomerAccountNo(String customerAccountNo) {
		this.customerAccountNo = customerAccountNo;
	}

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

}
